#!/usr/bin/env python
#This script selectes between translation or random draw of a sequence 

	Aminosequence = input 
	print ("Type 1 for translation or 2 for random codon selection.")
	options = input("1. Translation reinput sequence: \n -or- 2. Random selection reinput sequence: ")
#for those who selected 1
	if options = 1
		AminoSequence = []
		AminoSequence = AminoSequence [::-1]
	print (AminoSequence)

#Create complement strand
	if i = ("A")
		AminoSequence.append ("T")
	if i = ("T")
		AminoSequence.append ("A")
	if i = ("C")
		AminoSequence.append ("G")
	if i = ("G")
		AminoSequence.append ("C")
	print (AminoSequence)
#This transcripts DNA to RNA
        if i = ("A")
                AminoSequence.append ("U")
        print (AminoSequence)
        AminoSequence = RNA

#This creates codon
	Codon = [RNA[i:i:3]] for i in range(0, len(RNA), 3)
	Print Codon

#List of Codon to protein
	if Codon = { "UUU":"PHE","UUC":"PHE","UUA":"LEU","UUG":"LEU","UCU":"SER","UCC":"SER","UCA":"SER","UCG":"SER","UAU":"TYR","UAC":"TYR","UAA":"STOP","UAG":"STOP","UGU":"CYS","UGC":"CYS","UGA":"STOP","UGG":"TRP","CUU":"LEU","CUC":"LEU","CUA":"LEU","CUG":"LEU","CCU":"PRO","CCC":"PRO","CCA":"PRO","CCG":"PRO","CAU":"HIS","CAC":"HIS","CAA":"GLN","CAG":"GLN","CGU":"ARG","CGC":"ARG","CGA":"ARG","CGG":"ARG","AUU":"ILE","AUC":"ILE","AUA":"ILE","AUG":"MET-or-START","ACU":"THR","ACC":"THR","ACA":"THR","ACG":"THR","AAU":"ASN","ACC":"ASN","AAA":"LYS","AAG":"LYS","AGU":"SER","AGC":"SER","AGA":"ARG","AGG":"ARG","GUU":"VAL","GUC":"VAL","GUA":"VAL","GUG":"VAL","GCU":"ALA","GCC":"ALA","GCA":"ALA","GCG":"ALA","GAU":"ASP","GAC":"ASP","GAA":"GLU","GAG":"GLU","GGU":"GLY","GGC":"GLY","GGA":"GLY","GGA":"GLY","GGG":"GLY"}
	 print "" = ProteinSeq

#for those who selected 2
        if options = 2
                AminoSequence = []
                AminoSequence = AminoSequence [::-1]
        print (AminoSequence)

#Create complement strand
        if i = ("A")
                AminoSequence.append ("T")
        if i = ("T")
                AminoSequence.append ("A")
        if i = ("C")
                AminoSequence.append ("G")
        if i = ("G")
                AminoSequence.append ("C")
        print (AminoSequence)

#This transcripts DNA to RNA
       
	 if i = ("A")
                AminoSequence.append ("U")
        print (AminoSequence)
        AminoSequence = RNA
#This creates codon
        Codon = [RNA[i:i:3]] for i in range(0, len(RNA), 3)
	print Codon
#This randomly generates a codon from the sequence
	import random
	randomCodon = random.choice(Codon)
	print(randomCodon)
